### ISSUE TITLE
Backport Linux compilation fix

### ISSUE THREAD

**Issue by gee4vee** [OpenKitten/NioDNS#5]
Can we have this back ported to 1.x?
https://github.com/OpenKitten/NioDNS/pull/2

We are getting a compile failure in our Travis build:
https://travis-ci.org/IBM-Swift/generator-swiftserver/jobs/602887577?utm_medium=notification&utm_source=github_status

The dependency on NioDNS is coming from MongoDB which we rely on:
https://github.com/OpenKitten/MongoKitten/blob/master/5.0/Package.swift#L28

**Comment by Joannis** [comment]
Hey :) Yeah, we sure can. I'll try to do it tomorrow, but as I'm going to SSSconf it might be carried over the weekend. If you're able to get a PR up then that's cool, too 👍

**Comment by anatoliykant** [comment]
> Можем ли мы перенести это обратно на 1.x?
> [# 2](https://github.com/OpenKitten/NioDNS/pull/2)
> 
> Мы получаем ошибку компиляции в нашей сборке Travis:
> https://travis-ci.org/IBM-Swift/generator-swiftserver/jobs/602887577?utm_medium=notification&utm_source=github_status
> 
> Зависимость от NioDNS исходит от MongoDB, на которую мы опираемся:
> https://github.com/OpenKitten/MongoKitten/blob/master/5.0/Package.swift#L28

I have the same problem.
When I add the MongoKitten(https://github.com/OpenKitten/MongoKitten.git) package to the Vapor project, the project compiles for a very long time and gets stuck at https://github.com/openkitten/NioDNS.git.
When can you fix this?

I am using Mac OS 10.14.6, Xcode 11.2.1, Swift 5.1.2, Vapor Toolbox 3.1.10, MongoDB 4.2.1.

**Comment by Joannis** [comment]
I'm backporting it now @anatoliykant, @gee4vee

**Comment by Joannis** [comment]
@anatoliykant are you sure that it's the same problem? Geevee had a problem with compilation errors on Linux. What you're referring to sounds more like a (dependency) conflict somewhere.

**Comment by anatoliykant** [comment]
> @anatoliykant are you sure that it's the same problem? Geevee had a problem with compilation errors on Linux. What you're referring to sounds more like a (dependency) conflict somewhere.
You're right. I have a problem installing the package and it happens when you run the swift build command in the terminal so the mac OS.
Rather, there is a similar problem with the NioDNS package. Which for some reason is not installed.
Can I create a new issue?!

**Comment by Joannis** [comment]
Please do make a new issue :)
I'm not sure what's causing your issue, definitely try clearing the `.build` and/or `.swiftpm` folders. Those caches are known to cause issues sometimes.
